server:
  port: 9518
  context-path: /store

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9000/eureka

validateQuery: SELECT 1
spring: 
  thymeleaf: 
    mode: LEGACYHTML5
  datasource:
    driver: com.mysql.jdbc.Driver
    #mysql8:0     com.mysql.cj.jdbc.Driver  
    #mysql5.0     com.mysql.jdbc.Driver
    url: jdbc:mysql:///mystorebase?userSSL=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    #mysql5.0     jdbc:mysql://111.230.210.85:3306/mystorebase
    #mysql8:0  jdbc:mysql://111.230.210.85:3306/mystorebase?userSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    #?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: 123456
  application:
    name: store-web
  resources:
    static-locations: classpath:/static/
    
feign:
  hystrix:
    enabled: true
#redis: 
#  hostName: 127.0.0.1
#  port: 6379
#  maxIdle: 300
#  maxTotal: 1000
#  maxWaitMillis: 1000
#  minEvictableIdleTimeMillis: 300000
#  numTestsPerEvictionRun: 1024
#  timeBetweenEvictionRunsMillis: 30000
#  testOnBorrow: true
#  testWhileIdle: true    
    
 