server:
  port: 9519
  context-path: /store
  max-http-header-size: 1024000






eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9000/eureka

logging:
  level:
    com.chuenyee: debug

spring:
  application:
    name: store-fileServer


